config/routes.rb
Rails.application.routes.draw do
  get 'ims/main'
  devise_for :users
  resources :users
  get 'home/index'
  resources :sales do
    collection do
      get 'stock_report', to: 'sales#stock_report'
    end
  end
  resources :purchases
  resources :products do
    get 'getProduct', to: 'products#getProduct'
  end
  resources :suppliers do
    get 'products', to: 'suppliers#products'
  end
  root "home#index"

  get 'ims/chart_data', to: 'ims#chart_data'
  get 'getProduct', to: 'products#getProduct'
  

end

app/controllers/ims_controller.rb
# app/controllers/ims_controller.rb

class ImsController < ApplicationController

  def main
    @supplier_data = Supplier.count
    @product_data = Product.count
    @customer_data = Sale.select(:customer_name).distinct.count
    @user_data = User.count

  end

  def chart_data
      user_data = User.group_by_day(:created_at).count
      purchase_data = Purchase.joins(:product).group('products.name', 'DATE(purchases.created_at)').count
      product_data = ActiveRecord::Base.connection.execute("SELECT s.\"name\", ARRAY_AGG(p.name) AS product_names, COUNT(*) AS product_count FROM products p left join suppliers s on p.supplier_id = s.id  GROUP BY s.\"name\"")
      pie_data = product_data.map do |data|
        product_names = data["product_names"].scan(/"([^"]*)"/).flatten
        {
          supplier_name: data["name"],
          product_names: product_names,
          product_count: data["product_count"]
        }
      end

      sale_data = Sale.joins(:product).group('products.name').group_by_day_of_week('sales.created_at', format: "%a").select('products.name, COUNT(*) as count, MAX(sales.created_at) as created_at').order('count DESC')
      sale_data = sale_data.map do |entry|
        name = entry.name
        count = entry.count
        created_at = entry.created_at
        next if name.nil? || count.nil? || created_at.nil?
        [name, count, Date.parse(created_at.strftime('%Y-%m-%d')).wday] 
      end

      
    line_chart_data = ActiveRecord::Base.connection.execute("SELECT p2.name AS name, jsonb_object_agg(date, purchase_count) AS data FROM ( SELECT p.product_id, p.date, COUNT(p.date) AS purchase_count FROM purchases p GROUP BY p.product_id, p.date ) AS subquery LEFT JOIN products p2 ON subquery.product_id = p2.id GROUP BY p2.name;")
    line_data =  line_chart_data.map{|pdata| {name: pdata["name"], data: pdata["data"]}}
    chart_data = {
      user_counts_by_day: user_data,
      purchase_counts_by_day: line_data,
      product_counts_by_day: pie_data,
      sale_counts_by_day_of_week: sale_data,
    }

    render json: chart_data
  end


end

app/helpers/ims_helper.rb
module ImsHelper
end

app/views/ims/_nav.html.erb
<style>
   .report-list {
   display: none;
}
.report-list.active {
   display: block;
}
</style>
<aside id="default-sidebar" class=" left-0 w-[14rem] min-h-screen transition-transform -translate-x-full sm:translate-x-0" aria-label="Sidebar">
   <div class="h-full px-3 py-4 overflow-y-auto bg-gray-50">
      <ul class="space-y-2 font-medium">
         <li>
            <%= link_to root_path, class: "flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group" do %>
               <%= tag.i(class: "fa-solid fa-house") %>
               <span class="ml-3">Dashboard</span>
            <% end %>
         </li>
         <li>
            <%= link_to suppliers_path, class: "flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group" do %>
            <%= tag.i(class: "fa-solid fa-truck") %>
            <span class="flex-1 ml-3 whitespace-nowrap">Supplier</span>
            <% end %>
         </li>
         <li>
            <%= link_to products_path, class: "flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group" do %>
            <%= tag.i(class: "fa-solid fa-boxes-stacked") %>
            <span class="flex-1 ml-3 whitespace-nowrap">Products</span>
            <% end %>
         </li>
         <li>
            <%= link_to new_purchase_path, class: "flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group" do %>
         <%= tag.i(class: "fa-regular fa-money-bill-1") %>
         <span class="flex-1 ml-3 whitespace-nowrap">Purchase</span>
         <% end %>
         </li>
         <li>
            <%= link_to new_sale_path, class: "flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group" do %>
            <%= tag.i(class: "fa-brands fa-sellsy") %>
            <span class="flex-1 ml-3 whitespace-nowrap">Sales</span>
            <% end %>
         </li>

         <li>
            <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg hover:bg-gray-100 group mb-4 report-link">
            <i class="fa-solid fa-chart-pie"></i>
            <span class="flex-1 ml-3 whitespace-nowrap">Report<i class="fa-solid fa-angle-down ml-5"></i></span>
            </a>
            <ul class="report-list hidden text-gray-600">
                  <li class="ml-10 text-md"><%= link_to 'Purchase Report', purchases_path %></li>
                  <li class="mt-2 ml-10 text-md"><%= link_to 'Sales Report', sales_path %></li>
            </ul>
         </li>  
      </ul>
   </div>
</aside>



<script>
//for dropdown of report
   $(document).ready(function() {
      $(".report-link").click(function(e) {
         e.preventDefault();
         $(".report-list").toggleClass("active");
      });
   });
</script>

app/views/ims/main.html.erb
<body class="flex bg-gray-100 min-h-screen">
    <main class="p-6 space-y-6">
      <section class="grid grid-cols-4 gap-6">
        <div class="flex items-center p-8 bg-white shadow rounded-lg">
          <div class="inline-flex flex-shrink-0 items-center justify-center text-4xl h-16 w-16 text-purple-600 bg-purple-100 rounded-full mr-6">
           <i class="fa-solid fa-parachute-box"></i>
          </div>
          <div>
            <span class="block text-2xl font-bold"><%= @supplier_data %></span>
            <span class="block text-gray-500">Suppliers</span>
          </div>
        </div>
        <div class="flex items-center p-8 bg-white shadow rounded-lg">
          <div class="inline-flex flex-shrink-0 items-center justify-center text-4xl h-16 w-16 text-green-600 bg-green-100 rounded-full mr-6">
            <i class="fa-solid fa-boxes-stacked"></i>
          </div>
          <div>
            <span class="block text-2xl font-bold"><%= @product_data %></span>
            <span class="block text-gray-500">Products</span>
          </div>
        </div>
        <div class="flex items-center p-8 bg-white shadow rounded-lg">
          <div class="inline-flex flex-shrink-0 items-center justify-center text-4xl h-16 w-16 text-red-600 bg-red-100 rounded-full mr-6">
            <i class="fa-solid fa-users"></i>
          </div>
          <div>
            <span class="inline-block text-2xl font-bold"><%= @customer_data%></span>
            <span class="block text-gray-500">Costumers</span>
          </div>
        </div>
        <div class="flex items-center p-8 bg-white shadow rounded-lg">
          <div class="inline-flex flex-shrink-0 items-center text-4xl justify-center h-16 w-16 text-blue-600 bg-blue-100 rounded-full mr-6">
            <i class="fa-regular fa-user"></i>
          </div>
          <div>
            <span class="block text-2xl font-bold"><%= @user_data %></span>
            <span class="block text-gray-500">Users</span>
          </div>
        </div>
      </section>  
      <section class="grid md:grid-cols-2 xl:grid-cols-4 xl:grid-rows-3 xl:grid-flow-col gap-6">
      <!--Line chart -->
        <div class="flex flex-col md:col-span-3 md:row-span-3 bg-white shadow rounded-lg">
          <div class="px-6 py-5 font-semibold border-b border-gray-100">Purchases</div>
          <div class="p-4 flex-grow">
            <div class="flex h-full px-4 w-full text-gray-400 text-3xl font-semibold rounded-md">
                <div class="w-full" id="purchase-chart-container"></div> 
            </div>
          </div>
        </div>

        
        <div class="flex flex-col row-span-3 bg-white shadow rounded-lg overflow-hidden">
          <div class="px-6 py-5 font-semibold border-b border-gray-100">Suppliers</div>
          <div class="p-4 flex-grow">
            <div class="flex items-center justify-center text-gray-400 text-3xl font-semibold  rounded-md">
              <div id="product-chart-container"></div>
            </div>
          </div>
        </div>
      </section>
      <section class="grid grid-cols-4 gap-6 h-full">
       <div class="flex flex-col md:col-span-4 md:row-span-4 bg-white shadow rounded-lg">
        <div class="px-6 py-5 font-semibold border-b border-gray-100">Sales Data</div>
        <div class="p-4 flex-grow">
        <div class="flex items-center justify-center text-gray-400 text-3xl font-semibold  rounded-md">
          <div class="w-full h-80" id="sale-chart-container"></div>
          </div>
          </div>
        </div>
      </section>

    </main>
  </div>
</body>

<script>
  $(document).ready(function() {
    function fetchChartData() {
      $.ajax({
        url: '/ims/chart_data',
        type: 'GET',
        dataType: 'json',
        success: function(data) {
          const linechartData = data.purchase_counts_by_day.map(item => ({
            name: item.name,
            data: JSON.parse(item.data)
          }));
          new Chartkick.LineChart('purchase-chart-container', linechartData, {
            xtitle: 'Date',
            ytitle: 'Purchase Count'
          });

        var pieChartData = data.product_counts_by_day.map(item => {
            return [item.supplier_name, item.product_count, item.product_names];
        });
        new Chartkick.PieChart('product-chart-container', pieChartData, {
          library: {
            tooltips: {
                callbacks: {
                    label: function (tooltipItem, data) {
                        var dataset = data.datasets[tooltipItem.datasetIndex];
                        var index = tooltipItem.index;
                        return dataset.productNames[index];
                    }
                }
            }
        }
        });

          


          new Chartkick.ColumnChart('sale-chart-container', data.sale_counts_by_day_of_week, {
            title: 'Sales Data no of sales',
            xtitle: 'Porduct name',
            ytitle: 'No. of sales'
          });
        },
        error: function(xhr, status, error) {
          console.error('Error fetching chart data:', error);
        }
      });
    }

    fetchChartData();

    $('#refresh-charts-button').on('click', function() {
      fetchChartData();
    });
  });
</script>