config/routes.rb
Rails.application.routes.draw do
  get 'ims/main'
  devise_for :users
  resources :users
  get 'home/index'
  resources :sales do
    collection do
      get 'stock_report', to: 'sales#stock_report'
    end
  end
  resources :purchases
  resources :products do
    get 'getProduct', to: 'products#getProduct'
  end
  resources :suppliers do
    get 'products', to: 'suppliers#products'
  end
  root "home#index"

  get 'ims/chart_data', to: 'ims#chart_data'
  get 'getProduct', to: 'products#getProduct'
  

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :supplier
  has_many :purchases
  validates :name, uniqueness: { scope: :supplier_id, message: "Product already exists for the same supplier" }

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:getProduct]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
    product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    cost_price = params["product"]["cost_price"].to_i
    selling_price = params["product"]["selling_price"].to_i
    respond_to do |format|
      if cost_price < selling_price
        if @product.save
          format.html { redirect_to product_url(@product), flash: { message: "Product created successfully", type: "success"} }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to new_product_path, flash: { message: "Selling price can't be less than cost price", type: "error" } }
      format.json { head :no_content }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def getProduct
    product = Product.find(params[:product_id])
    cost_price = product.cost_price
    selling_price = product.selling_price
    render json: { id: product.id,cost_price: cost_price, selling_price: selling_price }
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:supplier_id, :name, :cost_price, :selling_price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :supplier_id,"Supplier Name", style: "display: block", class:"form-label "  %>
    <%= form.collection_select :supplier_id, Supplier.all, :id, :name, { include_blank: "Select" }, { class: "bg-white form-input" } %>
  </div>
  <div>
    <% form.label :supplier_name, style: "display: block", class:"form-label "  %>
    <% form.text_field :supplier_name, class:"form-input" %>
  </div>

  <div>
    <%= form.label :name, style: "display: block", class:"form-label "  %>
    <%= form.text_field :name, class:"form-input" %>
  </div>

  <div>
    <%= form.label :cost_price, style: "display: block", class:"form-label "  %>
    <%= form.number_field :cost_price, step: "any", class:"form-input", id: "cost_price" %>
  </div>

  <div>
    <%= form.label :selling_price, style: "display: block", class:"form-label "  %>
    <%= form.number_field :selling_price, step: "any", class:"form-input", id: "selling_price" %>
    <p class="error text-red-500 mt-1 mb-3"></p>
  </div>
  <div>
    <%= form.submit class:"btn-submit" %>
  </div>
<% end %>

<script>
    $(document).ready(function () {
    $("#selling_price").on('change', function (event) {
        var costPrice = parseFloat($("#cost_price").val());
        var sellingPrice = parseFloat($("#selling_price").val());
        console.log(costPrice);
        console.log(sellingPrice);

        if (sellingPrice < costPrice) {
            $(".error").text("Selling price cannot be less than cost price");
             event.preventDefault();
        } else {
            $(".error").text("");
        }
    });
});
</script>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Supplier:</strong>
    <%= product.supplier_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Cost price:</strong>
    <%= product.cost_price %>
  </p>

  <p>
    <strong>Selling price:</strong>
    <%= product.selling_price %>
  </p>

</div>

app/views/products/edit.html.erb
<div class="w-[81%] absolute">
  <h1 class=" bg-slate-300 py-4 mt-4 rounded-md font-bold text-3xl px-4">Editing product</h1>
    <%= render "form", product: @product %><br> 
  <div>
    <%= link_to "Back", products_path, class:"btn-back" %>
  </div>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="w-[80%] absolute">
  <div class="mt-4">
    <h1 class="mb-4 text-4xl font-bold" >Products</h1>
  </div>
  <div class="mb-4"><%= link_to "New product", new_product_path, class: "bg-blue-300 px-2 py-2 rounded" %></div>
  <div class="relative overflow-x-auto shadow-md" >
    <table class="w-full text-md text-left text-gray-700">
      <thead class="text-xl text-gray-700 uppercase bg-gray-50">
        <tr>
          <th class="px-6 py-3">Supplier Name</th>
          <th class="px-6 py-3">Product Name</th>
          <th class="px-6 py-3">Cost Price</th>
          <th class="px-6 py-3">Selling Price</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr class="bg-white border-b hover:bg-gray-300">
            <td class="px-6 py-3"><%= product.supplier.name %></td>
            <td class="px-6 py-3"><%= link_to product.name, product_path(product) %></td>
            <td class="px-6 py-3"><%= product.cost_price %></td>
            <td class="px-6 py-3"><%= product.selling_price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/products/new.html.erb
<% if flash[:message] %>
<div class="p-4 mt-2 mb-2 text-sm <%= flash[:type] == 'error' ? 'text-red-600' : 'text-green-600' %> rounded-lg bg-gray-50" role="alert">
  <span class="font-medium"><%= flash[:message] %></span>
</div>
<% end %>
<div class="w-[81%] absolute pr-4">
  <h1 class=" bg-slate-300 py-4 text-re mt-4 rounded-md font-bold text-3xl px-4">New product</h1>
  
  <div class="mt-2 pr-4"><%= render "form", product: @product %></div>
  <br>
  <div>
    <%= link_to "Back", products_path, class:"bg-gray-500 py-2 px-3 rounded-md text-slate-100" %>
  </div>
</div>

app/views/products/show.html.erb
<div class="w-[81%] absolute bg-slate-50 pl-3 py-5 mt-4 rounded-md shadow-lg">
  <div class="pl-4">
    <div class="mt-1">
      <% if flash[:message] %>
      <div class="w-[90%]">
        <div class="px-3   py-4 text-sm <%= flash[:type] == 'error' ? 'text-red-600' : 'text-green-600' %> rounded-lg bg-gray-200" role="alert">
          <span class="font-medium"><%= flash[:message] %></span>
        </div>
      </div>
      <%end %>
      <%= render @product %>
    </div>
    
    <div class='mt-3'>
      <%= link_to "Edit", edit_product_path(@product),class:"bg-green-300 btn-show" %> |
      <%= link_to "Back", products_path, class:"btn-back" %>
      <%= button_to "Destroy", @product, method: :delete, class:"btn-delete mt-4" %>
    </div>
  </div>
</div>