config/routes.rb
Rails.application.routes.draw do
  get 'ims/main'
  devise_for :users
  resources :users
  get 'home/index'
  resources :sales do
    collection do
      get 'stock_report', to: 'sales#stock_report'
    end
  end
  resources :purchases
  resources :products do
    get 'getProduct', to: 'products#getProduct'
  end
  resources :suppliers do
    get 'products', to: 'suppliers#products'
  end
  root "home#index"

  get 'ims/chart_data', to: 'ims#chart_data'
  get 'getProduct', to: 'products#getProduct'
  

end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :products
  has_many :purchases

  validates :name, presence: true, length: { maximum: 100 }, format: { with: /\A[a-zA-Z\s]+\z/, message: "should only contain letters" }

  validates :number, presence: true, length: { maximum: 20 }, format: { with: /\A(98\d{8}|011\d{6})\z/, message: "should be in the format 98xxxxxxxx or 011xxxxxx",} ,numericality: { only_integer: true }

  validates :address, presence: true, length: { maximum: 200 }
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:products]

  # GET /suppliers or /suppliers.json
  def index
    @suppliers = Supplier.all
  end

  # GET /suppliers/1 or /suppliers/1.json
  def show
  end

  # GET /suppliers/new
  def new
    @supplier = Supplier.new
  end

  # GET /suppliers/1/edit
  def edit
  end

  # POST /suppliers or /suppliers.json
  def create
    @supplier = Supplier.new(supplier_params)
  
    respond_to do |format|
      if @supplier.valid?
        if Supplier.exists?(name: @supplier.name) && Supplier.exists?(number: @supplier.number)
          format.html { redirect_to new_supplier_path, flash: { message: "Supplier with the same name or number already exists.", type: "error" } }
          format.json { render json: @supplier.errors, status: :unprocessable_entity }
        else
          if @supplier.save
            format.html { redirect_to supplier_url(@supplier), flash: { message: "Supplier was successfully created.", type: "success" } }
            format.json { render :show, status: :created, location: @supplier }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @supplier.errors, status: :unprocessable_entity }
          end
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # PATCH/PUT /suppliers/1 or /suppliers/1.json
  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to supplier_url(@supplier), notice: "Supplier was successfully updated." }
        format.json { render :show, status: :ok, location: @supplier }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1 or /suppliers/1.json
  def destroy
    @supplier.destroy

    respond_to do |format|
      format.html { redirect_to suppliers_url, notice: "Supplier was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def products
    supplier = Supplier.find(params[:supplier_id])
    products = supplier.products
    render json: products, only: [:id, :name]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def supplier_params
      params.require(:supplier).permit(:name, :number, :address, :description)
    end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/_form.html.erb
  <%= form_with(model: supplier, id: "supplier-form") do |form| %>
    <div>
      <%= form.label :name, class:"form-label " %>
      <%= form.text_field :name, class: "form-input", id: "supplier_name" %>
      <% if supplier.errors.has_key?(:name) %>
        <div class="error-message text-red-500">
          <%= "Name " +supplier.errors[:name].first %>
        </div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :number, class:"form-label" %>
      <%= form.text_field :number, class: "form-input", id: "supplier_number" %>
      <% if supplier.errors.has_key?(:number) %>
        <div class="error-message text-red-500">
          <%= supplier.errors[:number].first %>
        </div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :address, class:"form-label" %>
      <%= form.text_field :address, class: "form-input", id: "supplier_address" %>
      <% if supplier.errors.has_key?(:address) %>
        <div class="error-message text-red-500">
          <%= supplier.errors[:address].first %>
        </div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :discription, class:"form-label" %>
      <%= form.text_area :discription, class:"form-input scrollbar-hide" %>
    </div>
    <div>
      <%= form.submit class:"btn-submit" %>
    </div>
  <% end %>

app/views/suppliers/_supplier.html.erb
<div id="<%= dom_id supplier %>">
  <p>
    <strong>Name:</strong>
    <%= supplier.name %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= supplier.number %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= supplier.address %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= supplier.description %>
  </p>

</div>

app/views/suppliers/edit.html.erb
<div class="w-[81%] absolute">
  <h1 class=" bg-slate-300 py-4 mt-4 rounded-md font-bold text-3xl px-4">Edit supplier</h1>
  <%= render "form", supplier: @supplier %><br>
  <div>
    <%= link_to "Back", suppliers_path, class:"btn-back" %>
  </div>
</div>

app/views/suppliers/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="w-[80%] absolute">
  <div class="mt-4">
    <h1 class="mb-4 text-4xl font-bold" >Suppliers</h1>
  </div>
  <div class="mb-4"><%= link_to "New Suppplier", new_supplier_path, class: "bg-blue-300 px-2 py-2 rounded" %></div>
  <div class="relative overflow-x-auto shadow-md" >
    <table class="w-full text-md text-left text-gray-700">
      <thead class="text-xl text-gray-700 uppercase bg-gray-50">
          <tr>
              <th class="px-6 py-3">Supplier name</th>
              <th class="px-6 py-3">Contact</th>
              <th class="px-6 py-3">Address</th>
              <th class="px-6 py-3">Action</th>
          </tr>
      </thead>
      <tbody>
            <% @suppliers.each do |supplier|%>
              <tr class="bg-white border-b hover:bg-gray-300">
                <td class="px-6 py-4"> <%= link_to supplier.name, supplier_path(supplier) %> </td>
                <td class="px-6 py-4"> <%= link_to supplier.number, supplier_path(supplier) %></td>
                <td class="px-6 py-4"> <%= link_to supplier.address, supplier_path(supplier) %> </td>
                <div>
                  <td class="px-6 py-4 flex">
                    <%= link_to "Edit", edit_supplier_path(supplier), class:"bg-green-300 btn-show mr-2" %>
                    <%= button_to "Destroy", supplier, method: :delete, class:"btn-delete" %>
                  </td>
                </div>
              </tr>
            <%end%>
          </tbody>
    </table>
  </div>
</div>

app/views/suppliers/new.html.erb
<div class="w-[81%] absolute pr-5">
<% if flash[:message] %>
  <div class="p-4 mt-2 mb-2 text-sm <%= flash[:type] == 'error' ? 'text-red-600' : 'text-green-600' %> rounded-lg bg-gray-50" role="alert">
    <span class="font-medium"><%= flash[:message] %></span>
  </div>
<% end %>
  <h1 class=" bg-slate-300 py-4 mt-4 rounded-md font-bold text-3xl pl-4 ">Create Supplier</h1>
  <div class="mt-2 pr-3">
  <%= render "form", supplier: @supplier %>
  </div>
  <br>
  <div>
    <%= link_to "Back", suppliers_path, class:"bg-gray-500 py-2 px-3 rounded-md text-slate-100" %>
</div>
</div>

app/views/suppliers/show.html.erb
<div class="w-[81%] absolute bg-slate-50 pl-3 py-5 mt-4 rounded-md shadow-lg">
  <div class="mt-6">
    <% if flash[:message] %>
      <div class="w-[90%]">
        <div class="px-3   py-4 text-sm <%= flash[:type] == 'error' ? 'text-red-600' : 'text-green-600' %> rounded-lg bg-gray-200" role="alert">
          <span class="font-medium"><%= flash[:message] %></span>
        </div>
      </div>
    <%end %>
    <%= render @supplier %>
  </div>
  
  <div>
    <div class="mt-3">
      <%= link_to "Edit", edit_supplier_path(@supplier), class:"bg-green-300 btn-show" %>
      <%= link_to "Back", suppliers_path, class:"btn-back" %>
    </div>
    </div>
</div>